//
//  Page.h
//  DemokratiAppen
//
//  Created by Silvia Man on 2014-01-12.
//  Copyright (c) 2014 Demokratiappen
//

#import <UIKit/UIKit.h>
#import <Parse/Parse.h>

@interface Page : PFObject <PFSubclassing>

@property NSString *title;
@property NSString *url;
@property PFUser *user;
//@property int negative_tags;
//@property int positive_tags;

//@property NSDate createdAt;  //automatically generated by PFOjbect to server

+ (NSString*) parseClassName;

@end
